% This function has only really one specific function.
% It opens up the .hdf files from the Terra and Aqua MODIS satellites and
% will return the dataset(s) asked of it inside a struct.
% it has been specifically targeted as a global dataset, in that values only
% change on a daily basis. Furthermore, the monthly AOD_550_Dark_Target_Deep_Blue_Combined_Mean_Mean
% will be returned should it exist.
% The function first establishes the correct hdf files. It is assumed that
% the MODIS_data_store contains 3 folders, MOD08_D3, MYD08_D3 and MOD08_M3.
% These are all available from the ftp LAADS server:
% ftp://ladsweb.modaps.eosdis.nasa.gov/archive/allData/6/MOD08_D3.. etc.
% The opening part of this function navigates the native file format of
% this ftp server to identify whether the satellite images exist. Should
% none of the files exist, the function will return an empty struct. 
% The fucntion will then process the Terra and Aqua satellites in turn. A
% variable_marker is used to indicate whether an attempt at blending these
% two satellite datasets should occur, and should both exist, this will
% happen. The outputs is therefore blended data from both satellites. Both
% satellites obey the same data sets, and so this blending works nicely and
% often differs for a good few pixels.
% This function cannot handle a string of time series. The only output are
% single daily summaries, some outputs are 1D, 2D, 3D and 4D. This function
% can tolerate making a mean of any format, though does not attempt for 1D
% as they are the same for both satellites. 
% There is an additional try-catch that will attempt to load a file that
% exists. It appears that filezilla can cause some corruptions with
% downloads, though infrequently (potentially due to interruption
% mid-download). The try-catch simply attempts to get the file ID for the
% file, should this fail, it is assumed the file is corrupted and will flag
% as non-existent. 
% The final important alteration that is made is to convert the integer
% stored data back into the original recorded format. Each variable is
% accompanied by a fill value, offset, scaling and a valid range. 
% Firstly, missing data are replaced with the fill value. The offset is
% then added to the integer. The scaling is then multiplied to each value.
% Lastly, the value is checked against the valid range. This is the data
% that is returned in the output data struct. 

% ------------------------ INFO --------------------------------------
% Created by: Jamie Bright
% Date: finished on 30/01/2018

% ------------------------ INPUTS --------------------------------------
% datestr_yyyymmdd - a date string in format 'yyyymmdd' e.g. '20160430'
%
% datafields - these must exactly match those within the hdf file with no
%              exceptions. See "FIELDS FOR POTENTIAL EXTRACTION" for
%              complete list.
% 
% MODIS_data_store - This is the file path as a string where the three
%              folders of MOD08_D3, MYD08_D3 and MOD08_M3 are stored. Note
%              that so long as one of the daily (D3) folders exist, this
%              function will still operate. M3 is only important for gap
%              filling using the monthly AOD. 

% ------------------------- OUTPUTS -----------------------------------
% Data - this is a struct containing vars matching the input datafields
% 
% Latitudes - this contains the latitudes for the gridded variables
% 
% Longitudes - this contains the longitudes for the gridded variables.
%
% Units - this contains a string of the units for the variable requested.
% 
% Long_name - This contains a string of the official long title of the
%             dataset requested.
%

% -------------------- SUPPORTING DOCUMENTATION ------------------------
% https://modis-images.gsfc.nasa.gov/MOD08_D3/format.html
% https://modis-images.gsfc.nasa.gov/_docs/L3_Statistics_Table_C6.pdf
% http://hdfeos.org/zoo/LAADS/MOD08_D3_Cloud_Fraction_Liquid.m
% http://instesre.org/Aerosols/angstrom.htm

% -------------- FIELDS FOR POTENTIAL EXTRACTION -----------------
% datasets={'Solar_Zenith_Mean';'Solar_Zenith_Standard_Deviation';'Solar_Zenith_Minimum';'Solar_Zenith_Maximum';'Solar_Zenith_Pixel_Counts';'Solar_Azimuth_Mean';'Solar_Azimuth_Standard_Deviation';'Solar_Azimuth_Minimum';'Solar_Azimuth_Maximum';'Solar_Azimuth_Pixel_Counts';'Sensor_Zenith_Mean';'Sensor_Zenith_Standard_Deviation';'Sensor_Zenith_Minimum';'Sensor_Zenith_Maximum';'Sensor_Zenith_Pixel_Counts';'Sensor_Azimuth_Mean';'Sensor_Azimuth_Standard_Deviation';'Sensor_Azimuth_Minimum';'Sensor_Azimuth_Maximum';'Sensor_Azimuth_Pixel_Counts';'Aerosol_Scattering_Angle_Mean';'Aerosol_Scattering_Angle_Standard_Deviation';'Aerosol_Scattering_Angle_Minimum';'Aerosol_Scattering_Angle_Maximum';'Aerosol_Scattering_Angle_Pixel_Counts';'Aerosol_Scattering_Angle_Histogram_Counts';'Aerosol_Avg_Cloud_Distance_Land_Ocean_Mean';'Aerosol_Avg_Cloud_Distance_Land_Ocean_Standard_Deviation';'Aerosol_Avg_Cloud_Distance_Land_Ocean_Minimum';'Aerosol_Avg_Cloud_Distance_Land_Ocean_Maximum';'Aerosol_Avg_Cloud_Distance_Land_Ocean_Pixel_Counts';'Aerosol_Optical_Depth_Land_Ocean_Mean';'Aerosol_Optical_Depth_Land_Ocean_Standard_Deviation';'Aerosol_Optical_Depth_Land_Ocean_Minimum';'Aerosol_Optical_Depth_Land_Ocean_Maximum';'Aerosol_Optical_Depth_Land_Ocean_Pixel_Counts';'Aerosol_Optical_Depth_Land_Ocean_Histogram_Counts';'Aerosol_Optical_Depth_Land_Mean';'Aerosol_Optical_Depth_Land_Standard_Deviation';'Aerosol_Optical_Depth_Land_Minimum';'Aerosol_Optical_Depth_Land_Maximum';'Aerosol_Optical_Depth_Land_QA_Mean';'Aerosol_Optical_Depth_Land_QA_Standard_Deviation';'Aerosol_Optical_Depth_Land_Histogram_Counts';'Aerosol_Optical_Depth_Land_Confidence_Histogram';'Aerosol_Number_Pixels_Used_Land_Mean';'Aerosol_Number_Pixels_Used_Land_Standard_Deviation';'Aerosol_Number_Pixels_Used_Land_Minimum';'Aerosol_Number_Pixels_Used_Land_Maximum';'Aerosol_Number_Pixels_Used_Land_QA_Mean';'Aerosol_Number_Pixels_Used_Land_QA_Standard_Deviation';'Aerosol_Number_Pixels_Used_Land_Histogram_Counts';'Deep_Blue_Aerosol_Optical_Depth_Land_Mean';'Deep_Blue_Aerosol_Optical_Depth_Land_Standard_Deviation';'Deep_Blue_Aerosol_Optical_Depth_Land_Minimum';'Deep_Blue_Aerosol_Optical_Depth_Land_Maximum';'Deep_Blue_Aerosol_Optical_Depth_Land_Histogram_Counts';'Deep_Blue_Aerosol_Optical_Depth_550_Land_Mean';'Deep_Blue_Aerosol_Optical_Depth_550_Land_Standard_Deviation';'Deep_Blue_Aerosol_Optical_Depth_550_Land_Minimum';'Deep_Blue_Aerosol_Optical_Depth_550_Land_Maximum';'Deep_Blue_Aerosol_Optical_Depth_550_Land_Histogram_Counts';'Deep_Blue_Angstrom_Exponent_Land_Mean';'Deep_Blue_Angstrom_Exponent_Land_Standard_Deviation';'Deep_Blue_Angstrom_Exponent_Land_Minimum';'Deep_Blue_Angstrom_Exponent_Land_Maximum';'Deep_Blue_Angstrom_Exponent_Land_Histogram_Counts';'Deep_Blue_Single_Scattering_Albedo_Land_Mean';'Deep_Blue_Single_Scattering_Albedo_Land_Standard_Deviation';'Deep_Blue_Single_Scattering_Albedo_Land_Minimum';'Deep_Blue_Single_Scattering_Albedo_Land_Maximum';'Deep_Blue_Single_Scattering_Albedo_Land_Histogram_Counts';'Deep_Blue_Number_Pixels_Used_550_Land_Mean';'Deep_Blue_Number_Pixels_Used_550_Land_Standard_Deviation';'Deep_Blue_Number_Pixels_Used_550_Land_Minimum';'Deep_Blue_Number_Pixels_Used_550_Land_Maximum';'Deep_Blue_Number_Pixels_Used_550_Land_Histogram_Counts';'AOD_550_Dark_Target_Deep_Blue_Combined_Mean';'AOD_550_Dark_Target_Deep_Blue_Combined_Standard_Deviation';'AOD_550_Dark_Target_Deep_Blue_Combined_Minimum';'AOD_550_Dark_Target_Deep_Blue_Combined_Maximum';'AOD_550_Dark_Target_Deep_Blue_Combined_Histogram_Counts';'Aerosol_Optical_Depth_Average_Ocean_Mean';'Aerosol_Optical_Depth_Average_Ocean_Standard_Deviation';'Aerosol_Optical_Depth_Average_Ocean_Minimum';'Aerosol_Optical_Depth_Average_Ocean_Maximum';'Aerosol_Optical_Depth_Average_Ocean_QA_Mean';'Aerosol_Optical_Depth_Average_Ocean_QA_Standard_Deviation';'Aerosol_Optical_Depth_Average_Ocean_Histogram_Counts';'Aerosol_Optical_Depth_Average_Ocean_Confidence_Histogram';'Aerosol_Optical_Depth_Small_Ocean_Mean';'Aerosol_Optical_Depth_Small_Ocean_Standard_Deviation';'Aerosol_Optical_Depth_Small_Ocean_Minimum';'Aerosol_Optical_Depth_Small_Ocean_Maximum';'Aerosol_Optical_Depth_Small_Ocean_QA_Mean';'Aerosol_Optical_Depth_Small_Ocean_QA_Standard_Deviation';'Aerosol_Optical_Depth_Small_Ocean_Histogram_Counts';'Aerosol_Optical_Depth_Small_Ocean_Confidence_Histogram';'Aerosol_PSML003_Ocean_Mean';'Aerosol_PSML003_Ocean_Standard_Deviation';'Aerosol_PSML003_Ocean_Minimum';'Aerosol_PSML003_Ocean_Maximum';'Aerosol_PSML003_Ocean_QA_Mean';'Aerosol_PSML003_Ocean_QA_Standard_Deviation';'Aerosol_PSML003_Ocean_Histogram_Counts';'Aerosol_PSML003_Ocean_Confidence_Histogram';'Aerosol_Optical_Depth_by_models_ocean_Mean';'Aerosol_Optical_Depth_by_models_ocean_Standard_Deviation';'Aerosol_Optical_Depth_by_models_ocean_Minimum';'Aerosol_Optical_Depth_by_models_ocean_Maximum';'Aerosol_Optical_Depth_by_models_ocean_QA_Mean';'Aerosol_Optical_Depth_by_models_ocean_QA_Standard_Deviation';'Aerosol_Optical_Depth_by_models_ocean_Confidence_Histogram';'Aerosol_Number_Pixels_Used_Ocean_Mean';'Aerosol_Number_Pixels_Used_Ocean_Standard_Deviation';'Aerosol_Number_Pixels_Used_Ocean_Minimum';'Aerosol_Number_Pixels_Used_Ocean_Maximum';'Aerosol_Number_Pixels_Used_Ocean_QA_Mean';'Aerosol_Number_Pixels_Used_Ocean_QA_Standard_Deviation';'Aerosol_Number_Pixels_Used_Ocean_Histogram_Counts';'Aerosol_AE1_Ocean_JHisto_vs_Opt_Depth';'Aerosol_AE2_Ocean_JHisto_vs_Opt_Depth';'Aerosol_OD_Ratio_Small_Ocean_055_JHisto_vs_Opt_Depth';'Water_Vapor_Near_Infrared_Clear_Mean';'Water_Vapor_Near_Infrared_Clear_Standard_Deviation';'Water_Vapor_Near_Infrared_Clear_Minimum';'Water_Vapor_Near_Infrared_Clear_Maximum';'Water_Vapor_Near_Infrared_Clear_Histogram_Counts';'Water_Vapor_Near_Infrared_Clear_Confidence_Histogram';'Water_Vapor_Near_Infrared_Cloud_Mean';'Water_Vapor_Near_Infrared_Cloud_Standard_Deviation';'Water_Vapor_Near_Infrared_Cloud_Minimum';'Water_Vapor_Near_Infrared_Cloud_Maximum';'Water_Vapor_Near_Infrared_Cloud_Histogram_Counts';'Water_Vapor_Near_Infrared_Cloud_Confidence_Histogram';'Cirrus_Reflectance_Mean';'Cirrus_Reflectance_Standard_Deviation';'Cirrus_Reflectance_Minimum';'Cirrus_Reflectance_Maximum';'Cirrus_Reflectance_Histogram_Counts';'Cirrus_Fraction_SWIR';'Cirrus_Fraction_SWIR_Pixel_Counts';'Cloud_Top_Temperature_Mean';'Cloud_Top_Temperature_Standard_Deviation';'Cloud_Top_Temperature_Minimum';'Cloud_Top_Temperature_Maximum';'Cloud_Top_Temperature_Pixel_Counts';'Cloud_Top_Temperature_JHisto_vs_Pressure';'Cloud_Top_Temperature_Day_Mean';'Cloud_Top_Temperature_Day_Standard_Deviation';'Cloud_Top_Temperature_Day_Minimum';'Cloud_Top_Temperature_Day_Maximum';'Cloud_Top_Temperature_Day_Pixel_Counts';'Cloud_Top_Temperature_Day_JHisto_vs_Pressure';'Cloud_Top_Temperature_Night_Mean';'Cloud_Top_Temperature_Night_Standard_Deviation';'Cloud_Top_Temperature_Night_Minimum';'Cloud_Top_Temperature_Night_Maximum';'Cloud_Top_Temperature_Night_Pixel_Counts';'Cloud_Top_Temperature_Night_JHisto_vs_Pressure';'Cloud_Top_Temperature_Nadir_Mean';'Cloud_Top_Temperature_Nadir_Standard_Deviation';'Cloud_Top_Temperature_Nadir_Minimum';'Cloud_Top_Temperature_Nadir_Maximum';'Cloud_Top_Temperature_Nadir_Pixel_Counts';'Cloud_Top_Temperature_Nadir_JHisto_vs_Pressure';'Cloud_Top_Temperature_Nadir_Day_Mean';'Cloud_Top_Temperature_Nadir_Day_Standard_Deviation';'Cloud_Top_Temperature_Nadir_Day_Minimum';'Cloud_Top_Temperature_Nadir_Day_Maximum';'Cloud_Top_Temperature_Nadir_Day_Pixel_Counts';'Cloud_Top_Temperature_Nadir_Day_JHisto_vs_Pressure';'Cloud_Top_Temperature_Nadir_Night_Mean';'Cloud_Top_Temperature_Nadir_Night_Standard_Deviation';'Cloud_Top_Temperature_Nadir_Night_Minimum';'Cloud_Top_Temperature_Nadir_Night_Maximum';'Cloud_Top_Temperature_Nadir_Night_Pixel_Counts';'Cloud_Top_Temperature_Nadir_Night_JHisto_vs_Pressure';'Cloud_Top_Pressure_Mean';'Cloud_Top_Pressure_Standard_Deviation';'Cloud_Top_Pressure_Minimum';'Cloud_Top_Pressure_Maximum';'Cloud_Top_Pressure_Pixel_Counts';'Cloud_Top_Pressure_Histogram_Counts';'Cloud_Top_Pressure_JHisto_vs_Emissivity';'Cloud_Top_Pressure_Day_Mean';'Cloud_Top_Pressure_Day_Standard_Deviation';'Cloud_Top_Pressure_Day_Minimum';'Cloud_Top_Pressure_Day_Maximum';'Cloud_Top_Pressure_Day_Pixel_Counts';'Cloud_Top_Pressure_Day_Histogram_Counts';'Cloud_Top_Pressure_Day_JHisto_vs_Emissivity';'Cloud_Top_Pressure_Night_Mean';'Cloud_Top_Pressure_Night_Standard_Deviation';'Cloud_Top_Pressure_Night_Minimum';'Cloud_Top_Pressure_Night_Maximum';'Cloud_Top_Pressure_Night_Pixel_Counts';'Cloud_Top_Pressure_Night_Histogram_Counts';'Cloud_Top_Pressure_Night_JHisto_vs_Emissivity';'Cloud_Top_Pressure_Nadir_Mean';'Cloud_Top_Pressure_Nadir_Standard_Deviation';'Cloud_Top_Pressure_Nadir_Minimum';'Cloud_Top_Pressure_Nadir_Maximum';'Cloud_Top_Pressure_Nadir_Pixel_Counts';'Cloud_Top_Pressure_Nadir_Histogram_Counts';'Cloud_Top_Pressure_Nadir_Day_Mean';'Cloud_Top_Pressure_Nadir_Day_Standard_Deviation';'Cloud_Top_Pressure_Nadir_Day_Minimum';'Cloud_Top_Pressure_Nadir_Day_Maximum';'Cloud_Top_Pressure_Nadir_Day_Pixel_Counts';'Cloud_Top_Pressure_Nadir_Day_Histogram_Counts';'Cloud_Top_Pressure_Nadir_Night_Mean';'Cloud_Top_Pressure_Nadir_Night_Standard_Deviation';'Cloud_Top_Pressure_Nadir_Night_Minimum';'Cloud_Top_Pressure_Nadir_Night_Maximum';'Cloud_Top_Pressure_Nadir_Night_Pixel_Counts';'Cloud_Top_Pressure_Nadir_Night_Histogram_Counts';'Cloud_Effective_Emissivity_Mean';'Cloud_Effective_Emissivity_Standard_Deviation';'Cloud_Effective_Emissivity_Minimum';'Cloud_Effective_Emissivity_Maximum';'Cloud_Effective_Emissivity_Pixel_Counts';'Cloud_Effective_Emissivity_JHisto_vs_Pressure';'Cloud_Effective_Emissivity_Day_Mean';'Cloud_Effective_Emissivity_Day_Standard_Deviation';'Cloud_Effective_Emissivity_Day_Minimum';'Cloud_Effective_Emissivity_Day_Maximum';'Cloud_Effective_Emissivity_Day_Pixel_Counts';'Cloud_Effective_Emissivity_Day_JHisto_vs_Pressure';'Cloud_Effective_Emissivity_Night_Mean';'Cloud_Effective_Emissivity_Night_Standard_Deviation';'Cloud_Effective_Emissivity_Night_Minimum';'Cloud_Effective_Emissivity_Night_Maximum';'Cloud_Effective_Emissivity_Night_Pixel_Counts';'Cloud_Effective_Emissivity_Night_JHisto_vs_Pressure';'Cloud_Effective_Emissivity_Nadir_Mean';'Cloud_Effective_Emissivity_Nadir_Standard_Deviation';'Cloud_Effective_Emissivity_Nadir_Minimum';'Cloud_Effective_Emissivity_Nadir_Maximum';'Cloud_Effective_Emissivity_Nadir_Pixel_Counts';'Cloud_Effective_Emissivity_Nadir_JHisto_vs_Pressure';'Cloud_Effective_Emissivity_Nadir_Day_Mean';'Cloud_Effective_Emissivity_Nadir_Day_Standard_Deviation';'Cloud_Effective_Emissivity_Nadir_Day_Minimum';'Cloud_Effective_Emissivity_Nadir_Day_Maximum';'Cloud_Effective_Emissivity_Nadir_Day_Pixel_Counts';'Cloud_Effective_Emissivity_Nadir_Day_JHisto_vs_Pressure';'Cloud_Effective_Emissivity_Nadir_Night_Mean';'Cloud_Effective_Emissivity_Nadir_Night_Standard_Deviation';'Cloud_Effective_Emissivity_Nadir_Night_Minimum';'Cloud_Effective_Emissivity_Nadir_Night_Maximum';'Cloud_Effective_Emissivity_Nadir_Night_Pixel_Counts';'Cloud_Effective_Emissivity_Nadir_Night_JHisto_vs_Pressure';'Cloud_Fraction_Mean';'Cloud_Fraction_Standard_Deviation';'Cloud_Fraction_Minimum';'Cloud_Fraction_Maximum';'Cloud_Fraction_Pixel_Counts';'Cloud_Fraction_JHisto_vs_Pressure';'Cloud_Fraction_Day_Mean';'Cloud_Fraction_Day_Standard_Deviation';'Cloud_Fraction_Day_Minimum';'Cloud_Fraction_Day_Maximum';'Cloud_Fraction_Day_Pixel_Counts';'Cloud_Fraction_Day_JHisto_vs_Pressure';'Cloud_Fraction_Night_Mean';'Cloud_Fraction_Night_Standard_Deviation';'Cloud_Fraction_Night_Minimum';'Cloud_Fraction_Night_Maximum';'Cloud_Fraction_Night_Pixel_Counts';'Cloud_Fraction_Night_JHisto_vs_Pressure';'Cloud_Fraction_Nadir_Mean';'Cloud_Fraction_Nadir_Standard_Deviation';'Cloud_Fraction_Nadir_Minimum';'Cloud_Fraction_Nadir_Maximum';'Cloud_Fraction_Nadir_Pixel_Counts';'Cloud_Fraction_Nadir_JHisto_vs_Pressure';'Cloud_Fraction_Nadir_Day_Mean';'Cloud_Fraction_Nadir_Day_Standard_Deviation';'Cloud_Fraction_Nadir_Day_Minimum';'Cloud_Fraction_Nadir_Day_Maximum';'Cloud_Fraction_Nadir_Day_Pixel_Counts';'Cloud_Fraction_Nadir_Day_JHisto_vs_Pressure';'Cloud_Fraction_Nadir_Night_Mean';'Cloud_Fraction_Nadir_Night_Standard_Deviation';'Cloud_Fraction_Nadir_Night_Minimum';'Cloud_Fraction_Nadir_Night_Maximum';'Cloud_Fraction_Nadir_Night_Pixel_Counts';'Cloud_Fraction_Nadir_Night_JHisto_vs_Pressure';'Cloud_Top_Height_Mean';'Cloud_Top_Height_Standard_Deviation';'Cloud_Top_Height_Minimum';'Cloud_Top_Height_Maximum';'Cloud_Top_Height_JHisto_vs_Pressure';'Cloud_Top_Height_Day_Mean';'Cloud_Top_Height_Day_Standard_Deviation';'Cloud_Top_Height_Day_Minimum';'Cloud_Top_Height_Day_Maximum';'Cloud_Top_Height_Day_JHisto_vs_Pressure';'Cloud_Top_Height_Night_Mean';'Cloud_Top_Height_Night_Standard_Deviation';'Cloud_Top_Height_Night_Minimum';'Cloud_Top_Height_Night_Maximum';'Cloud_Top_Height_Night_JHisto_vs_Pressure';'Cloud_Top_Height_Nadir_Mean';'Cloud_Top_Height_Nadir_Standard_Deviation';'Cloud_Top_Height_Nadir_Minimum';'Cloud_Top_Height_Nadir_Maximum';'Cloud_Top_Height_Nadir_Pixel_Counts';'Cloud_Top_Height_Nadir_JHisto_vs_Pressure';'Cloud_Top_Height_Nadir_Day_Mean';'Cloud_Top_Height_Nadir_Day_Standard_Deviation';'Cloud_Top_Height_Nadir_Day_Minimum';'Cloud_Top_Height_Nadir_Day_Maximum';'Cloud_Top_Height_Nadir_Day_Pixel_Counts';'Cloud_Top_Height_Nadir_Day_JHisto_vs_Pressure';'Cloud_Top_Height_Nadir_Night_Mean';'Cloud_Top_Height_Nadir_Night_Standard_Deviation';'Cloud_Top_Height_Nadir_Night_Minimum';'Cloud_Top_Height_Nadir_Night_Maximum';'Cloud_Top_Height_Nadir_Night_Pixel_Counts';'Cloud_Top_Height_Nadir_Night_JHisto_vs_Pressure';'Cirrus_Fraction_Infrared';'Cirrus_Fraction_Infrared_Pixel_Counts';'High_Cloud_Fraction_Infrared';'High_Cloud_Fraction_Infrared_Pixel_Counts';'Cloud_Phase_Infrared_Histogram_Counts';'Cloud_Phase_Infrared_Day_Histogram_Counts';'Cloud_Phase_Infrared_Day_JHisto_vs_Pressure';'Cloud_Phase_Infrared_Day_JHisto_vs_Temperature';'Cloud_Phase_Infrared_Night_Histogram_Counts';'Cloud_Phase_Infrared_Night_JHisto_vs_Pressure';'Cloud_Phase_Infrared_Night_JHisto_vs_Temperature';'Cloud_Top_Pressure_1km_Nadir_Day_JHisto_vs_Pressure';'Cloud_Top_Pressure_1km_Nadir_Night_JHisto_vs_Pressure';'Sunglint_Fraction_Day';'Sunglint_Fraction_Day_Pixel_Counts';'Snow_Fraction_Spectral_Under_Thin_Clouds_Day';'Snow_Fraction_Spectral_Under_Thin_Clouds_Day_Pixel_Counts';'Snow_Fraction_Ancillary_Under_All_Clouds_Night';'Snow_Fraction_Ancillary_Under_All_Clouds_Night_Pixel_Counts';'Ocean_Fraction_Day';'Ocean_Fraction_Day_Pixel_Counts';'Ocean_Fraction_Night';'Ocean_Fraction_Night_Pixel_Counts';'Coast_Fraction_Day';'Coast_Fraction_Day_Pixel_Counts';'Coast_Fraction_Night';'Coast_Fraction_Night_Pixel_Counts';'Desert_Fraction_Day';'Desert_Fraction_Day_Pixel_Counts';'Desert_Fraction_Night';'Desert_Fraction_Night_Pixel_Counts';'Land_Fraction_Day';'Land_Fraction_Day_Pixel_Counts';'Land_Fraction_Night';'Land_Fraction_Night_Pixel_Counts';'Cloud_Optical_Thickness_Liquid_Mean';'Cloud_Optical_Thickness_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_Liquid_Minimum';'Cloud_Optical_Thickness_Liquid_Maximum';'Cloud_Optical_Thickness_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_Liquid_Log_Mean_Uncertainty';'Cloud_Optical_Thickness_Liquid_Log_Mean';'Cloud_Optical_Thickness_Liquid_Log_Standard_Deviation';'Cloud_Optical_Thickness_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_Liquid_JHisto_vs_Eff_Radius';'Cloud_Optical_Thickness_Liquid_JHisto_vs_Temperature';'Cloud_Optical_Thickness_Liquid_JHisto_vs_Pressure';'Cloud_Optical_Thickness_Ice_Mean';'Cloud_Optical_Thickness_Ice_Standard_Deviation';'Cloud_Optical_Thickness_Ice_Minimum';'Cloud_Optical_Thickness_Ice_Maximum';'Cloud_Optical_Thickness_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_Ice_Log_Mean_Uncertainty';'Cloud_Optical_Thickness_Ice_Log_Mean';'Cloud_Optical_Thickness_Ice_Log_Standard_Deviation';'Cloud_Optical_Thickness_Ice_Histogram_Counts';'Cloud_Optical_Thickness_Ice_JHisto_vs_Eff_Radius';'Cloud_Optical_Thickness_Ice_JHisto_vs_Temperature';'Cloud_Optical_Thickness_Ice_JHisto_vs_Pressure';'Cloud_Optical_Thickness_Ice_JHisto_vs_Emissivity';'Cloud_Optical_Thickness_Undetermined_Mean';'Cloud_Optical_Thickness_Undetermined_Standard_Deviation';'Cloud_Optical_Thickness_Undetermined_Minimum';'Cloud_Optical_Thickness_Undetermined_Maximum';'Cloud_Optical_Thickness_Undetermined_Log_Mean';'Cloud_Optical_Thickness_Undetermined_Log_Standard_Deviation';'Cloud_Optical_Thickness_Combined_Mean';'Cloud_Optical_Thickness_Combined_Standard_Deviation';'Cloud_Optical_Thickness_Combined_Minimum';'Cloud_Optical_Thickness_Combined_Maximum';'Cloud_Optical_Thickness_Combined_Log_Mean';'Cloud_Optical_Thickness_Combined_Log_Standard_Deviation';'Cloud_Optical_Thickness_PCL_Liquid_Mean';'Cloud_Optical_Thickness_PCL_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_PCL_Liquid_Minimum';'Cloud_Optical_Thickness_PCL_Liquid_Maximum';'Cloud_Optical_Thickness_PCL_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_PCL_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_PCL_Liquid_JHisto_vs_Eff_Radius';'Cloud_Optical_Thickness_PCL_Ice_Mean';'Cloud_Optical_Thickness_PCL_Ice_Standard_Deviation';'Cloud_Optical_Thickness_PCL_Ice_Minimum';'Cloud_Optical_Thickness_PCL_Ice_Maximum';'Cloud_Optical_Thickness_PCL_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_PCL_Ice_Histogram_Counts';'Cloud_Optical_Thickness_PCL_Ice_JHisto_vs_Eff_Radius';'Cloud_Optical_Thickness_PCL_Undetermined_Mean';'Cloud_Optical_Thickness_PCL_Undetermined_Standard_Deviation';'Cloud_Optical_Thickness_PCL_Undetermined_Minimum';'Cloud_Optical_Thickness_PCL_Undetermined_Maximum';'Cloud_Optical_Thickness_PCL_Combined_Mean';'Cloud_Optical_Thickness_PCL_Combined_Standard_Deviation';'Cloud_Optical_Thickness_PCL_Combined_Minimum';'Cloud_Optical_Thickness_PCL_Combined_Maximum';'Cloud_Optical_Thickness_ISCCP_JHisto_vs_Pressure';'Cloud_Optical_Thickness_PCL_ISCCP_JHisto_vs_Pressure';'Cloud_Effective_Radius_Liquid_Mean';'Cloud_Effective_Radius_Liquid_Standard_Deviation';'Cloud_Effective_Radius_Liquid_Minimum';'Cloud_Effective_Radius_Liquid_Maximum';'Cloud_Effective_Radius_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_Liquid_Histogram_Counts';'Cloud_Effective_Radius_Liquid_JHisto_vs_Temperature';'Cloud_Effective_Radius_Liquid_JHisto_vs_Pressure';'Cloud_Effective_Radius_Ice_Mean';'Cloud_Effective_Radius_Ice_Standard_Deviation';'Cloud_Effective_Radius_Ice_Minimum';'Cloud_Effective_Radius_Ice_Maximum';'Cloud_Effective_Radius_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_Ice_Histogram_Counts';'Cloud_Effective_Radius_Ice_JHisto_vs_Temperature';'Cloud_Effective_Radius_Ice_JHisto_vs_Pressure';'Cloud_Effective_Radius_Undetermined_Mean';'Cloud_Effective_Radius_Undetermined_Standard_Deviation';'Cloud_Effective_Radius_Undetermined_Minimum';'Cloud_Effective_Radius_Undetermined_Maximum';'Cloud_Effective_Radius_PCL_Liquid_Mean';'Cloud_Effective_Radius_PCL_Liquid_Standard_Deviation';'Cloud_Effective_Radius_PCL_Liquid_Minimum';'Cloud_Effective_Radius_PCL_Liquid_Maximum';'Cloud_Effective_Radius_PCL_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_PCL_Liquid_Histogram_Counts';'Cloud_Effective_Radius_PCL_Ice_Mean';'Cloud_Effective_Radius_PCL_Ice_Standard_Deviation';'Cloud_Effective_Radius_PCL_Ice_Minimum';'Cloud_Effective_Radius_PCL_Ice_Maximum';'Cloud_Effective_Radius_PCL_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_PCL_Ice_Histogram_Counts';'Cloud_Effective_Radius_PCL_Undetermined_Mean';'Cloud_Effective_Radius_PCL_Undetermined_Standard_Deviation';'Cloud_Effective_Radius_PCL_Undetermined_Minimum';'Cloud_Effective_Radius_PCL_Undetermined_Maximum';'Cloud_Water_Path_Liquid_Mean';'Cloud_Water_Path_Liquid_Standard_Deviation';'Cloud_Water_Path_Liquid_Minimum';'Cloud_Water_Path_Liquid_Maximum';'Cloud_Water_Path_Liquid_Mean_Uncertainty';'Cloud_Water_Path_Liquid_Histogram_Counts';'Cloud_Water_Path_Ice_Mean';'Cloud_Water_Path_Ice_Standard_Deviation';'Cloud_Water_Path_Ice_Minimum';'Cloud_Water_Path_Ice_Maximum';'Cloud_Water_Path_Ice_Mean_Uncertainty';'Cloud_Water_Path_Ice_Histogram_Counts';'Cloud_Water_Path_Undetermined_Mean';'Cloud_Water_Path_Undetermined_Standard_Deviation';'Cloud_Water_Path_Undetermined_Minimum';'Cloud_Water_Path_Undetermined_Maximum';'Cloud_Water_Path_PCL_Liquid_Mean';'Cloud_Water_Path_PCL_Liquid_Standard_Deviation';'Cloud_Water_Path_PCL_Liquid_Minimum';'Cloud_Water_Path_PCL_Liquid_Maximum';'Cloud_Water_Path_PCL_Liquid_Mean_Uncertainty';'Cloud_Water_Path_PCL_Liquid_Histogram_Counts';'Cloud_Water_Path_PCL_Ice_Mean';'Cloud_Water_Path_PCL_Ice_Standard_Deviation';'Cloud_Water_Path_PCL_Ice_Minimum';'Cloud_Water_Path_PCL_Ice_Maximum';'Cloud_Water_Path_PCL_Ice_Mean_Uncertainty';'Cloud_Water_Path_PCL_Ice_Histogram_Counts';'Cloud_Water_Path_PCL_Undetermined_Mean';'Cloud_Water_Path_PCL_Undetermined_Standard_Deviation';'Cloud_Water_Path_PCL_Undetermined_Minimum';'Cloud_Water_Path_PCL_Undetermined_Maximum';'Cloud_Phase_Optical_Properties_JHisto_vs_Temperature';'COP_Phase_Cloudy_Histogram_Counts';'COP_Phase_Partly_Cloudy_Histogram_Counts';'COP_Phase_CloudMaskClear_Histogram_Counts';'COP_Phase_RestoredToClear_Histogram_Counts';'Cloud_Retrieval_Fraction_Liquid';'Cloud_Retrieval_Fraction_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_Ice';'Cloud_Retrieval_Fraction_Ice_Pixel_Counts';'Cloud_Retrieval_Fraction_Undetermined';'Cloud_Retrieval_Fraction_Undetermined_Pixel_Counts';'Cloud_Retrieval_Fraction_Combined';'Cloud_Retrieval_Fraction_Combined_Pixel_Counts';'Cloud_Retrieval_Fraction_PCL_Liquid';'Cloud_Retrieval_Fraction_PCL_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_PCL_Ice';'Cloud_Retrieval_Fraction_PCL_Ice_Pixel_Counts';'Cloud_Retrieval_Fraction_PCL_Undetermined';'Cloud_Retrieval_Fraction_PCL_Undetermined_Pixel_Counts';'Cloud_Retrieval_Fraction_PCL_Combined';'Cloud_Retrieval_Fraction_PCL_Combined_Pixel_Counts';'Cloud_Optical_Thickness_1L_Liquid_Mean';'Cloud_Optical_Thickness_1L_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_1L_Liquid_Minimum';'Cloud_Optical_Thickness_1L_Liquid_Maximum';'Cloud_Optical_Thickness_1L_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_1L_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_1L_Liquid_JHisto_vs_Eff_Radius';'Cloud_Optical_Thickness_1L_Ice_Mean';'Cloud_Optical_Thickness_1L_Ice_Standard_Deviation';'Cloud_Optical_Thickness_1L_Ice_Minimum';'Cloud_Optical_Thickness_1L_Ice_Maximum';'Cloud_Optical_Thickness_1L_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_1L_Ice_Histogram_Counts';'Cloud_Optical_Thickness_1L_Ice_JHisto_vs_Eff_Radius';'Cloud_Optical_Thickness_1L_Ice_JHisto_vs_Emissivity';'Cloud_Effective_Radius_1L_Liquid_Mean';'Cloud_Effective_Radius_1L_Liquid_Standard_Deviation';'Cloud_Effective_Radius_1L_Liquid_Minimum';'Cloud_Effective_Radius_1L_Liquid_Maximum';'Cloud_Effective_Radius_1L_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_1L_Liquid_Histogram_Counts';'Cloud_Effective_Radius_1L_Ice_Mean';'Cloud_Effective_Radius_1L_Ice_Standard_Deviation';'Cloud_Effective_Radius_1L_Ice_Minimum';'Cloud_Effective_Radius_1L_Ice_Maximum';'Cloud_Effective_Radius_1L_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_1L_Ice_Histogram_Counts';'Cloud_Water_Path_1L_Liquid_Mean';'Cloud_Water_Path_1L_Liquid_Standard_Deviation';'Cloud_Water_Path_1L_Liquid_Minimum';'Cloud_Water_Path_1L_Liquid_Maximum';'Cloud_Water_Path_1L_Liquid_Mean_Uncertainty';'Cloud_Water_Path_1L_Liquid_Histogram_Counts';'Cloud_Water_Path_1L_Ice_Mean';'Cloud_Water_Path_1L_Ice_Standard_Deviation';'Cloud_Water_Path_1L_Ice_Minimum';'Cloud_Water_Path_1L_Ice_Maximum';'Cloud_Water_Path_1L_Ice_Mean_Uncertainty';'Cloud_Water_Path_1L_Ice_Histogram_Counts';'Cloud_Phase_Optical_Properties1L_JHisto_vs_Temperature';'Cloud_Retrieval_Fraction_1L_Liquid';'Cloud_Retrieval_Fraction_1L_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_1L_Ice';'Cloud_Retrieval_Fraction_1L_Ice_Pixel_Counts';'Cloud_Retrieval_Fraction_ML_Liquid';'Cloud_Retrieval_Fraction_ML_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_ML_Ice';'Cloud_Retrieval_Fraction_ML_Ice_Pixel_Counts';'Cloud_Retrieval_Fraction_ML_Undetermined';'Cloud_Retrieval_Fraction_ML_Undetermined_Pixel_Counts';'Cloud_Retrieval_Fraction_ML_Combined';'Cloud_Retrieval_Fraction_ML_Combined_Pixel_Counts';'ML_Fraction_Liquid';'ML_Fraction_Liquid_Pixel_Counts';'ML_Fraction_Ice';'ML_Fraction_Ice_Pixel_Counts';'ML_Fraction_Undetermined';'ML_Fraction_Undetermined_Pixel_Counts';'ML_Fraction_Combined';'ML_Fraction_Combined_Pixel_Counts';'Cloud_Optical_Thickness_16_Liquid_Mean';'Cloud_Optical_Thickness_16_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_16_Liquid_Minimum';'Cloud_Optical_Thickness_16_Liquid_Maximum';'Cloud_Optical_Thickness_16_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_16_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_16_Liquid_JHisto_vs_Eff_Radius_16';'Cloud_Optical_Thickness_16_Ice_Mean';'Cloud_Optical_Thickness_16_Ice_Standard_Deviation';'Cloud_Optical_Thickness_16_Ice_Minimum';'Cloud_Optical_Thickness_16_Ice_Maximum';'Cloud_Optical_Thickness_16_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_16_Ice_Histogram_Counts';'Cloud_Optical_Thickness_16_Ice_JHisto_vs_Eff_Radius_16';'Cloud_Effective_Radius_16_Liquid_Mean';'Cloud_Effective_Radius_16_Liquid_Standard_Deviation';'Cloud_Effective_Radius_16_Liquid_Minimum';'Cloud_Effective_Radius_16_Liquid_Maximum';'Cloud_Effective_Radius_16_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_16_Liquid_Histogram_Counts';'Cloud_Effective_Radius_16_Liquid_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_16_Liquid_JHisto_vs_Temperature';'Cloud_Effective_Radius_16_Liquid_JHisto_vs_Eff_Radius_37';'Cloud_Effective_Radius_16_Ice_Mean';'Cloud_Effective_Radius_16_Ice_Standard_Deviation';'Cloud_Effective_Radius_16_Ice_Minimum';'Cloud_Effective_Radius_16_Ice_Maximum';'Cloud_Effective_Radius_16_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_16_Ice_Histogram_Counts';'Cloud_Effective_Radius_16_Ice_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_16_Ice_JHisto_vs_Temperature';'Cloud_Effective_Radius_16_Ice_JHisto_vs_Eff_Radius_37';'Cloud_Water_Path_16_Liquid_Mean';'Cloud_Water_Path_16_Liquid_Standard_Deviation';'Cloud_Water_Path_16_Liquid_Minimum';'Cloud_Water_Path_16_Liquid_Maximum';'Cloud_Water_Path_16_Liquid_Mean_Uncertainty';'Cloud_Water_Path_16_Liquid_Histogram_Counts';'Cloud_Water_Path_16_Ice_Mean';'Cloud_Water_Path_16_Ice_Standard_Deviation';'Cloud_Water_Path_16_Ice_Minimum';'Cloud_Water_Path_16_Ice_Maximum';'Cloud_Water_Path_16_Ice_Mean_Uncertainty';'Cloud_Water_Path_16_Ice_Histogram_Counts';'Cloud_Retrieval_Fraction_16_Liquid';'Cloud_Retrieval_Fraction_16_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_16_Ice';'Cloud_Retrieval_Fraction_16_Ice_Pixel_Counts';'Cloud_Optical_Thickness_16_PCL_Liquid_Mean';'Cloud_Optical_Thickness_16_PCL_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_16_PCL_Liquid_Minimum';'Cloud_Optical_Thickness_16_PCL_Liquid_Maximum';'Cloud_Optical_Thickness_16_PCL_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_16_PCL_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_16_PCL_Liquid_JHisto_vs_Eff_Radius_16';'Cloud_Optical_Thickness_16_PCL_Ice_Mean';'Cloud_Optical_Thickness_16_PCL_Ice_Standard_Deviation';'Cloud_Optical_Thickness_16_PCL_Ice_Minimum';'Cloud_Optical_Thickness_16_PCL_Ice_Maximum';'Cloud_Optical_Thickness_16_PCL_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_16_PCL_Ice_Histogram_Counts';'Cloud_Optical_Thickness_16_PCL_Ice_JHisto_vs_Eff_Radius_16';'Cloud_Effective_Radius_16_PCL_Liquid_Mean';'Cloud_Effective_Radius_16_PCL_Liquid_Standard_Deviation';'Cloud_Effective_Radius_16_PCL_Liquid_Minimum';'Cloud_Effective_Radius_16_PCL_Liquid_Maximum';'Cloud_Effective_Radius_16_PCL_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_16_PCL_Liquid_Histogram_Counts';'Cloud_Effective_Radius_16_PCL_Liquid_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_16_PCL_Liquid_JHisto_vs_Temperature';'Cloud_Effective_Radius_16_PCL_Liquid_JHisto_vs_Eff_Radius_37';'Cloud_Effective_Radius_16_PCL_Ice_Mean';'Cloud_Effective_Radius_16_PCL_Ice_Standard_Deviation';'Cloud_Effective_Radius_16_PCL_Ice_Minimum';'Cloud_Effective_Radius_16_PCL_Ice_Maximum';'Cloud_Effective_Radius_16_PCL_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_16_PCL_Ice_Histogram_Counts';'Cloud_Effective_Radius_16_PCL_Ice_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_16_PCL_Ice_JHisto_vs_Temperature';'Cloud_Effective_Radius_16_PCL_Ice_JHisto_vs_Eff_Radius_37';'Cloud_Water_Path_16_PCL_Liquid_Mean';'Cloud_Water_Path_16_PCL_Liquid_Standard_Deviation';'Cloud_Water_Path_16_PCL_Liquid_Minimum';'Cloud_Water_Path_16_PCL_Liquid_Maximum';'Cloud_Water_Path_16_PCL_Liquid_Mean_Uncertainty';'Cloud_Water_Path_16_PCL_Liquid_Histogram_Counts';'Cloud_Water_Path_16_PCL_Ice_Mean';'Cloud_Water_Path_16_PCL_Ice_Standard_Deviation';'Cloud_Water_Path_16_PCL_Ice_Minimum';'Cloud_Water_Path_16_PCL_Ice_Maximum';'Cloud_Water_Path_16_PCL_Ice_Mean_Uncertainty';'Cloud_Water_Path_16_PCL_Ice_Histogram_Counts';'Cloud_Retrieval_Fraction_16_PCL_Liquid';'Cloud_Retrieval_Fraction_16_PCL_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_16_PCL_Ice';'Cloud_Retrieval_Fraction_16_PCL_Ice_Pixel_Counts';'Cloud_Optical_Thickness_37_Liquid_Mean';'Cloud_Optical_Thickness_37_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_37_Liquid_Minimum';'Cloud_Optical_Thickness_37_Liquid_Maximum';'Cloud_Optical_Thickness_37_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_37_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_37_Liquid_JHisto_vs_Eff_Radius_37';'Cloud_Optical_Thickness_37_Ice_Mean';'Cloud_Optical_Thickness_37_Ice_Standard_Deviation';'Cloud_Optical_Thickness_37_Ice_Minimum';'Cloud_Optical_Thickness_37_Ice_Maximum';'Cloud_Optical_Thickness_37_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_37_Ice_Histogram_Counts';'Cloud_Optical_Thickness_37_Ice_JHisto_vs_Eff_Radius_37';'Cloud_Effective_Radius_37_Liquid_Mean';'Cloud_Effective_Radius_37_Liquid_Standard_Deviation';'Cloud_Effective_Radius_37_Liquid_Minimum';'Cloud_Effective_Radius_37_Liquid_Maximum';'Cloud_Effective_Radius_37_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_37_Liquid_Histogram_Counts';'Cloud_Effective_Radius_37_Liquid_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_37_Liquid_JHisto_vs_Temperature';'Cloud_Effective_Radius_37_Ice_Mean';'Cloud_Effective_Radius_37_Ice_Standard_Deviation';'Cloud_Effective_Radius_37_Ice_Minimum';'Cloud_Effective_Radius_37_Ice_Maximum';'Cloud_Effective_Radius_37_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_37_Ice_Histogram_Counts';'Cloud_Effective_Radius_37_Ice_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_37_Ice_JHisto_vs_Temperature';'Cloud_Water_Path_37_Liquid_Mean';'Cloud_Water_Path_37_Liquid_Standard_Deviation';'Cloud_Water_Path_37_Liquid_Minimum';'Cloud_Water_Path_37_Liquid_Maximum';'Cloud_Water_Path_37_Liquid_Mean_Uncertainty';'Cloud_Water_Path_37_Liquid_Histogram_Counts';'Cloud_Water_Path_37_Ice_Mean';'Cloud_Water_Path_37_Ice_Standard_Deviation';'Cloud_Water_Path_37_Ice_Minimum';'Cloud_Water_Path_37_Ice_Maximum';'Cloud_Water_Path_37_Ice_Mean_Uncertainty';'Cloud_Water_Path_37_Ice_Histogram_Counts';'Cloud_Retrieval_Fraction_37_Liquid';'Cloud_Retrieval_Fraction_37_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_37_Ice';'Cloud_Retrieval_Fraction_37_Ice_Pixel_Counts';'Cloud_Optical_Thickness_37_PCL_Liquid_Mean';'Cloud_Optical_Thickness_37_PCL_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_37_PCL_Liquid_Minimum';'Cloud_Optical_Thickness_37_PCL_Liquid_Maximum';'Cloud_Optical_Thickness_37_PCL_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_37_PCL_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_37_PCL_Liquid_JHisto_vs_Eff_Radius_37';'Cloud_Optical_Thickness_37_PCL_Ice_Mean';'Cloud_Optical_Thickness_37_PCL_Ice_Standard_Deviation';'Cloud_Optical_Thickness_37_PCL_Ice_Minimum';'Cloud_Optical_Thickness_37_PCL_Ice_Maximum';'Cloud_Optical_Thickness_37_PCL_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_37_PCL_Ice_Histogram_Counts';'Cloud_Optical_Thickness_37_PCL_Ice_JHisto_vs_Eff_Radius_37';'Cloud_Effective_Radius_37_PCL_Liquid_Mean';'Cloud_Effective_Radius_37_PCL_Liquid_Standard_Deviation';'Cloud_Effective_Radius_37_PCL_Liquid_Minimum';'Cloud_Effective_Radius_37_PCL_Liquid_Maximum';'Cloud_Effective_Radius_37_PCL_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_37_PCL_Liquid_Histogram_Counts';'Cloud_Effective_Radius_37_PCL_Liquid_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_37_PCL_Liquid_JHisto_vs_Temperature';'Cloud_Effective_Radius_37_PCL_Ice_Mean';'Cloud_Effective_Radius_37_PCL_Ice_Standard_Deviation';'Cloud_Effective_Radius_37_PCL_Ice_Minimum';'Cloud_Effective_Radius_37_PCL_Ice_Maximum';'Cloud_Effective_Radius_37_PCL_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_37_PCL_Ice_Histogram_Counts';'Cloud_Effective_Radius_37_PCL_Ice_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_37_PCL_Ice_JHisto_vs_Temperature';'Cloud_Water_Path_37_PCL_Liquid_Mean';'Cloud_Water_Path_37_PCL_Liquid_Standard_Deviation';'Cloud_Water_Path_37_PCL_Liquid_Minimum';'Cloud_Water_Path_37_PCL_Liquid_Maximum';'Cloud_Water_Path_37_PCL_Liquid_Mean_Uncertainty';'Cloud_Water_Path_37_PCL_Liquid_Histogram_Counts';'Cloud_Water_Path_37_PCL_Ice_Mean';'Cloud_Water_Path_37_PCL_Ice_Standard_Deviation';'Cloud_Water_Path_37_PCL_Ice_Minimum';'Cloud_Water_Path_37_PCL_Ice_Maximum';'Cloud_Water_Path_37_PCL_Ice_Mean_Uncertainty';'Cloud_Water_Path_37_PCL_Ice_Histogram_Counts';'Cloud_Retrieval_Fraction_37_PCL_Liquid';'Cloud_Retrieval_Fraction_37_PCL_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_37_PCL_Ice';'Cloud_Retrieval_Fraction_37_PCL_Ice_Pixel_Counts';'Cloud_Optical_Thickness_1621_Liquid_Mean';'Cloud_Optical_Thickness_1621_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_1621_Liquid_Minimum';'Cloud_Optical_Thickness_1621_Liquid_Maximum';'Cloud_Optical_Thickness_1621_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_1621_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_1621_Liquid_JHisto_vs_Eff_Radius';'Cloud_Optical_Thickness_1621_Ice_Mean';'Cloud_Optical_Thickness_1621_Ice_Standard_Deviation';'Cloud_Optical_Thickness_1621_Ice_Minimum';'Cloud_Optical_Thickness_1621_Ice_Maximum';'Cloud_Optical_Thickness_1621_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_1621_Ice_Histogram_Counts';'Cloud_Optical_Thickness_1621_Ice_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_1621_Liquid_Mean';'Cloud_Effective_Radius_1621_Liquid_Standard_Deviation';'Cloud_Effective_Radius_1621_Liquid_Minimum';'Cloud_Effective_Radius_1621_Liquid_Maximum';'Cloud_Effective_Radius_1621_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_1621_Liquid_Histogram_Counts';'Cloud_Effective_Radius_1621_Ice_Mean';'Cloud_Effective_Radius_1621_Ice_Standard_Deviation';'Cloud_Effective_Radius_1621_Ice_Minimum';'Cloud_Effective_Radius_1621_Ice_Maximum';'Cloud_Effective_Radius_1621_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_1621_Ice_Histogram_Counts';'Cloud_Water_Path_1621_Liquid_Mean';'Cloud_Water_Path_1621_Liquid_Standard_Deviation';'Cloud_Water_Path_1621_Liquid_Minimum';'Cloud_Water_Path_1621_Liquid_Maximum';'Cloud_Water_Path_1621_Liquid_Mean_Uncertainty';'Cloud_Water_Path_1621_Liquid_Histogram_Counts';'Cloud_Water_Path_1621_Ice_Mean';'Cloud_Water_Path_1621_Ice_Standard_Deviation';'Cloud_Water_Path_1621_Ice_Minimum';'Cloud_Water_Path_1621_Ice_Maximum';'Cloud_Water_Path_1621_Ice_Mean_Uncertainty';'Cloud_Water_Path_1621_Ice_Histogram_Counts';'Cloud_Retrieval_Fraction_1621_Liquid';'Cloud_Retrieval_Fraction_1621_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_1621_Ice';'Cloud_Retrieval_Fraction_1621_Ice_Pixel_Counts';'Cloud_Optical_Thickness_1621_PCL_Liquid_Mean';'Cloud_Optical_Thickness_1621_PCL_Liquid_Standard_Deviation';'Cloud_Optical_Thickness_1621_PCL_Liquid_Minimum';'Cloud_Optical_Thickness_1621_PCL_Liquid_Maximum';'Cloud_Optical_Thickness_1621_PCL_Liquid_Mean_Uncertainty';'Cloud_Optical_Thickness_1621_PCL_Liquid_Histogram_Counts';'Cloud_Optical_Thickness_1621_PCL_Liquid_JHisto_vs_Eff_Radius';'Cloud_Optical_Thickness_1621_PCL_Ice_Mean';'Cloud_Optical_Thickness_1621_PCL_Ice_Standard_Deviation';'Cloud_Optical_Thickness_1621_PCL_Ice_Minimum';'Cloud_Optical_Thickness_1621_PCL_Ice_Maximum';'Cloud_Optical_Thickness_1621_PCL_Ice_Mean_Uncertainty';'Cloud_Optical_Thickness_1621_PCL_Ice_Histogram_Counts';'Cloud_Optical_Thickness_1621_PCL_Ice_JHisto_vs_Eff_Radius';'Cloud_Effective_Radius_1621_PCL_Liquid_Mean';'Cloud_Effective_Radius_1621_PCL_Liquid_Standard_Deviation';'Cloud_Effective_Radius_1621_PCL_Liquid_Minimum';'Cloud_Effective_Radius_1621_PCL_Liquid_Maximum';'Cloud_Effective_Radius_1621_PCL_Liquid_Mean_Uncertainty';'Cloud_Effective_Radius_1621_PCL_Liquid_Histogram_Counts';'Cloud_Effective_Radius_1621_PCL_Ice_Mean';'Cloud_Effective_Radius_1621_PCL_Ice_Standard_Deviation';'Cloud_Effective_Radius_1621_PCL_Ice_Minimum';'Cloud_Effective_Radius_1621_PCL_Ice_Maximum';'Cloud_Effective_Radius_1621_PCL_Ice_Mean_Uncertainty';'Cloud_Effective_Radius_1621_PCL_Ice_Histogram_Counts';'Cloud_Water_Path_1621_PCL_Liquid_Mean';'Cloud_Water_Path_1621_PCL_Liquid_Standard_Deviation';'Cloud_Water_Path_1621_PCL_Liquid_Minimum';'Cloud_Water_Path_1621_PCL_Liquid_Maximum';'Cloud_Water_Path_1621_PCL_Liquid_Mean_Uncertainty';'Cloud_Water_Path_1621_PCL_Liquid_Histogram_Counts';'Cloud_Water_Path_1621_PCL_Ice_Mean';'Cloud_Water_Path_1621_PCL_Ice_Standard_Deviation';'Cloud_Water_Path_1621_PCL_Ice_Minimum';'Cloud_Water_Path_1621_PCL_Ice_Maximum';'Cloud_Water_Path_1621_PCL_Ice_Mean_Uncertainty';'Cloud_Water_Path_1621_PCL_Ice_Histogram_Counts';'Cloud_Retrieval_Fraction_1621_PCL_Liquid';'Cloud_Retrieval_Fraction_1621_PCL_Liquid_Pixel_Counts';'Cloud_Retrieval_Fraction_1621_PCL_Ice';'Cloud_Retrieval_Fraction_1621_PCL_Ice_Pixel_Counts';'Total_Ozone_Mean';'Total_Ozone_Standard_Deviation';'Total_Ozone_Minimum';'Total_Ozone_Maximum';'Total_Ozone_QA_Mean';'Total_Ozone_QA_Standard_Deviation';'Total_Ozone_Histogram_Counts';'Total_Ozone_Confidence_Histogram';'Total_Totals_Mean';'Total_Totals_Standard_Deviation';'Total_Totals_Minimum';'Total_Totals_Maximum';'Total_Totals_QA_Mean';'Total_Totals_QA_Standard_Deviation';'Total_Totals_Histogram_Counts';'Total_Totals_Confidence_Histogram';'Lifted_Index_Mean';'Lifted_Index_Standard_Deviation';'Lifted_Index_Minimum';'Lifted_Index_Maximum';'Lifted_Index_QA_Mean';'Lifted_Index_QA_Standard_Deviation';'Lifted_Index_Histogram_Counts';'Lifted_Index_Confidence_Histogram';'Atmospheric_Water_Vapor_Mean';'Atmospheric_Water_Vapor_Standard_Deviation';'Atmospheric_Water_Vapor_Minimum';'Atmospheric_Water_Vapor_Maximum';'Atmospheric_Water_Vapor_QA_Mean';'Atmospheric_Water_Vapor_QA_Standard_Deviation';'Atmospheric_Water_Vapor_Histogram_Counts';'Atmospheric_Water_Vapor_Confidence_Histogram';'Atmospheric_Water_Vapor_Low_Mean';'Atmospheric_Water_Vapor_Low_Standard_Deviation';'Atmospheric_Water_Vapor_Low_Minimum';'Atmospheric_Water_Vapor_Low_Maximum';'Atmospheric_Water_Vapor_Low_QA_Mean';'Atmospheric_Water_Vapor_Low_QA_Standard_Deviation';'Atmospheric_Water_Vapor_Low_Histogram_Counts';'Atmospheric_Water_Vapor_Low_Confidence_Histogram';'Atmospheric_Water_Vapor_High_Mean';'Atmospheric_Water_Vapor_High_Standard_Deviation';'Atmospheric_Water_Vapor_High_Minimum';'Atmospheric_Water_Vapor_High_Maximum';'Atmospheric_Water_Vapor_High_QA_Mean';'Atmospheric_Water_Vapor_High_QA_Standard_Deviation';'Atmospheric_Water_Vapor_High_Histogram_Counts';'Atmospheric_Water_Vapor_High_Confidence_Histogram';'Retrieved_Temperature_Profile_Mean';'Retrieved_Temperature_Profile_Standard_Deviation';'Retrieved_Temperature_Profile_Minimum';'Retrieved_Temperature_Profile_Maximum';'Retrieved_Temperature_Profile_Pixel_Counts';'Quality_Assurance_Categories';'Scattering_Angle_Histo_Intervals';'AOD_Histo_Intervals';'Corrected_Optical_Depth_Land_Micron_Levels';'Corrected_Optical_Depth_Land_Histo_Intervals';'Number_Pixels_Used_Histo_Intervals';'Number_Pixels_Used_Land_Micron_Levels';'Deep_Blue_Aerosol_Optical_Depth_Land_Micron_Levels';'Deep_Blue_Aerosol_Optical_Depth_Land_Histo_Intervals';'Deep_Blue_Angstrom_Exponent_Land_Histo_Intervals';'Deep_Blue_Single_Scattering_Albedo_Land_Histo_Intervals';'Effective_Optical_Depth_Average_Ocean_Micron_Levels';'Effective_Optical_Depth_Average_Ocean_Histo_Intervals';'Aerosol_PSML003_Ocean_Histo_Intervals';'Optical_Depth_by_models_ocean_Index';'Number_Pixels_Used_Ocean_Micron_Levels';'EOD_0p55um_Ocean_JHisto_Intervals';'AE1_Ocean_JHisto_Intervals';'AE2_Ocean_JHisto_Intervals';'ODRS_Ocean_JHisto_Intervals';'Water_Vapor_Near_Infrared_Clear_Histo_Intervals';'Water_Vapor_Near_Infrared_Cloud_Histo_Intervals';'Cirrus_Reflectance_Histo_Intervals';'Cloud_Top_Temperature_Histo_Intervals';'Cloud_Top_Pressure_Histo_Intervals';'CTP_Histo_Intervals';'Cloud_Top_Pressure_JHisto_Intervals';'CTP_JHisto_Intervals';'CTP_New_JHisto_Intervals';'CEE_JHisto_Intervals';'CEE2_JHisto_Intervals';'CEE_New_JHisto_Intervals';'CTP2_JHisto_Intervals';'CTH_JHisto_Intervals';'Cloud_Effective_Emissivity_JHisto_Intervals';'Cloud_Effective_Emissivity_Histo_Intervals';'Cloud_Fraction_Histo_Intervals';'CF_JHisto_Intervals';'CF_New_JHisto_Intervals';'Cloud_Phase_Infrared_JHisto_Intervals';'CP_New_Infrared_JHisto_Intervals';'Cloud_Phase_Infrared_Histo_Intervals';'CP_New_Infrared_Histo_Intervals';'Cloud_Top_Temperature_JHisto_Intervals';'CTT_New_JHisto_Intervals';'CTT_JHisto_Intervals';'CTP1km_JHisto_Intervals';'Cloud_Optical_Thickness_Liquid_Histo_Intervals';'COT_New_Liquid_Histo_Intervals';'Cloud_Optical_Thickness_Liquid_JHisto_Intervals';'COT_New_Liquid_JHisto_Intervals';'Cloud_Effective_Radius_Liquid_Histo_Intervals';'Cloud_Effective_Radius_Liquid_JHisto_Intervals';'Cloud_Top_Temperature_Liquid_JHisto_Intervals';'CTT_New_Liquid_JHisto_Intervals';'Cloud_Top_Pressure_Liquid_JHisto_Intervals';'CTP_New_Liquid_JHisto_Intervals';'Cloud_Optical_Thickness_Ice_Histo_Intervals';'COT_New_Ice_Histo_Intervals';'Cloud_Optical_Thickness_Ice_JHisto_Intervals';'COT_New_Ice_JHisto_Intervals';'Cloud_Effective_Radius_Ice_Histo_Intervals';'Cloud_Effective_Radius_Ice_JHisto_Intervals';'CER_New_Ice_JHisto_Intervals';'Cloud_Top_Temperature_Ice_JHisto_Intervals';'Cloud_Top_Pressure_Ice_JHisto_Intervals';'Cloud_Optical_Thickness_ISCCP_JHisto_Intervals';'COT_New_ISCCP_JHisto_Intervals';'Cloud_Top_Pressure_ISCCP_JHisto_Intervals';'Cloud_Phase_Optical_Properties_JHisto_Intervals';'COP_Phase_Cloud_Histo_Intervals';'COP_Phase_Clear_Histo_Intervals';'Cloud_Water_Path_Liquid_Histo_Intervals';'Cloud_Water_Path_Ice_Histo_Intervals';'Total_Ozone_Histo_Intervals';'Total_Totals_Histo_Intervals';'Lifted_Index_Histo_Intervals';'Atmospheric_Water_Vapor_Histo_Intervals';'Atmospheric_Water_Vapor_Low_Histo_Intervals';'Atmospheric_Water_Vapor_High_Histo_Intervals';'Pressure_Level';'XDim';'YDim'};
%
% You can copy and paste this into the console and explore the datasets
% cell matrix that is created. 

% -------------- ------------ EXAMPLE ----------------------------------
% This example plots the Angstrom Exponent as a mean from both Terra and 
% Aqua satellites

% datestr_yyyymmdd='20170625';
% 
% datafields={...
% 'Aerosol_Optical_Depth_Average_Ocean_Mean';'Effective_Optical_Depth_Average_Ocean_Micron_Levels';...
% 'Aerosol_Optical_Depth_Small_Ocean_Mean';...
% 'Aerosol_Optical_Depth_by_models_ocean_Mean';'Optical_Depth_by_models_ocean_Index';...
% 'Aerosol_Optical_Depth_Land_Mean';'Corrected_Optical_Depth_Land_Micron_Levels';...
% 'Aerosol_Optical_Depth_Land_Ocean_Mean';...
% 'Deep_Blue_Aerosol_Optical_Depth_Land_Mean';...
% 'Deep_Blue_Angstrom_Exponent_Land_Mean';...
% 'Deep_Blue_Aerosol_Optical_Depth_550_Land_Mean';...
% 'AOD_550_Dark_Target_Deep_Blue_Combined_Mean';...
% };
% 
%  MODIS_data_store='c:\projects\solcast-alpha\src\matlab\jamie-projects\MODIS\';
%    
% [data,latitudes,longitudes,units,long_name]=loadHDFEOS(datestr_yyyymmdd,datafields,MODIS_data_store);
% 
% % extract Angstrom Exponent: alpha=log(AOD1./AOD2)./log(lambda2./lambda1);
% alpha=data.Deep_Blue_Angstrom_Exponent_Land_Mean;
% alpha(isnan(alpha))=1.3; % this is an acceptable guess in absence of data.
% 
% AOD1_temp=data.AOD_550_Dark_Target_Deep_Blue_Combined_Mean;
% AOD2_temp=data.Aerosol_Optical_Depth_Land_Ocean_Mean;
% % find the total number of data at each pixel to divide by
% nan_count1=zeros(size(AOD1_temp))+~isnan(AOD1_temp);
% nan_count2=zeros(size(AOD2_temp))+~isnan(AOD2_temp);
% divider=nan_count1+nan_count2;
% % set NaNs to 0 for the addition
% AOD1_temp(isnan(AOD1_temp))=0;
% AOD2_temp(isnan(AOD2_temp))=0;
% % take a mean
% data.AOD=(AOD1_temp+AOD2_temp)./divider; %the divider will divide previously NaN values by 0, returning them to NaNs
% lambda=ones(size(data.AOD)).*0.55;% microns
% 
% % see if any AOD data exists in a different band other than 550nm
% dat=data.Aerosol_Optical_Depth_Land_Mean;
% % loop through each wave length
% for z=1:size(dat,3)
%     % load this wavelengths AOD data
%     assignin('base',['lev',num2str(z)],squeeze(dat(:,:,z)));
%     % if data is missing from AOD but not in this wavelength, then add then appropriate lambda and AOD value to the main matrix
%     lambda( (isnan(data.AOD) & ~isnan(eval(['lev',num2str(z)]))) )=data.Corrected_Optical_Depth_Land_Micron_Levels(z);
%     eval(['data.AOD((isnan(data.AOD)&~isnan(lev',num2str(z),')))=lev',num2str(z),'((isnan(data.AOD)&~isnan(lev',num2str(z),')));'])
% end
% 
% data.Angstrom_Beta=data.AOD./(lambda.^(-alpha));
% 
% % % plot the data
% datafields_to_plot=datafields;
% datafields_to_plot{end+1}='Angstrom_Beta';
% datafields_to_plot{end+1}='AOD';
% % Create the graphics figure.
% for i=1:length(datafields_to_plot)
%  plotOnMap(latitudes,longitudes,eval(['data.',datafields_to_plot{i}]),units{i},datafields_to_plot{i});%long_name{i})
% end

function [Data,Latitudes,Longitudes,Units,Long_name]=loadHDFEOS(datestr_yyyymmdd,datafields,MODIS_data_store)
try
% initialise the sd C API for HDF that exists in matlab
import matlab.io.hdf4.*
% open files from both the Terra(MOD) and Aqua(MYD) platforms

%establish the day of year
doy=datevec2doy(datevec(datestr_yyyymmdd,'yyyymmdd'));
switch length(num2str(doy))
    case 1
        doystr=['00',num2str(doy)];
    case 2        
        doystr=['0',num2str(doy)];
    case 3
        doystr=num2str(doy);
end

% search and extract the files within the appropriate folder path
dir_MYD=[MODIS_data_store,'MYD08_D3',filesep,datestr_yyyymmdd(1:4),filesep,doystr,filesep];
file_MYD=dir([dir_MYD,'MYD08_D3.A*']);
dir_MOD=[MODIS_data_store,'MOD08_D3',filesep,datestr_yyyymmdd(1:4),filesep,doystr,filesep];
file_MOD=dir([dir_MOD,'MOD08_D3.A',datestr_yyyymmdd(1:4),doystr,'*']);

% Check the files exist, so long as 1 does, this function will execute
if ~isempty(file_MYD)
    MYD_flag=1;
    filename_MYD=[dir_MYD,file_MYD(1).name];
        %these files are occasionally corrupted for some reason...
    try
          MYDID=matlab.io.hdf4.sd.start(filename_MYD);
          matlab.io.hdf4.sd.close(MYDID);
    catch err
      MYD_flag=0;
    end
    
else
    MYD_flag=0;
end

if ~isempty(file_MOD)
    MOD_flag=1;
    filename_MOD=[dir_MOD,file_MOD(1).name];
    try
        MODID=matlab.io.hdf4.sd.start(filename_MOD);
        matlab.io.hdf4.sd.close(MODID);
    catch err
        MOD_flag=0;
    end
    
else
    MOD_flag=0;
end

% % all the MYD and MOD versions have the same data types have identical format
%     % extract the hdf data with 'eos' specific for NASA file format
%     info=hdfinfo(filename{1},'eos');
%
%     % derive the total number of scientific data set (SDS)
%     num_of_sds=length(info.Grid.DataFields);
%
%     % pre-allocate a cell array to contain the SDS names
%     sds_names=cell(1,num_of_sds);
%
%     % loop through each SDS
%     for i=1:num_of_sds
%         % extract the name of each SDS
%         sds_names{i}=info.Grid.DataFields(i).Name;
%     end
%

%% Establish the datafields and include the XDim and YDim variables
sds_names=cell(1,2+length(datafields));
sds_names{1}='XDim';
sds_names{2}='YDim';
for i=3:2+length(datafields)
    sds_names{i}=datafields{i-2};
end
variable_marker=zeros(size(sds_names));

%% Process the Aqua MYD files
if MYD_flag==1
    
    % open the files
    MYD_id=matlab.io.hdf4.sd.start(filename_MYD);
    units=cell(1,length(sds_names));
    long_name=cell(1,length(sds_names));
    
    % loop through each SDS name,
    for i=1:length(sds_names)
        
        % extract the object index
        objIdx_MYD=matlab.io.hdf4.sd.nameToIndex(MYD_id,sds_names{i});
        
        % establish the SDS ID
        sdsID_MYD=matlab.io.hdf4.sd.select(MYD_id,objIdx_MYD);
        
        % load the data into memory
        MYD=double(matlab.io.hdf4.sd.readData(sdsID_MYD));
        
        if (sum([strcmp(sds_names{i},'XDim'),strcmp(sds_names{i},'YDim')])==0 && length(MYD)>45) %ignore XDim YDim and interval definitions (typcally 1X3/5/7/9 vectors)
            
            % Read fill value from the data field.
            fillvalue_index = matlab.io.hdf4.sd.findAttr(sdsID_MYD, '_FillValue');
            fillvalue=matlab.io.hdf4.sd.readAttr(sdsID_MYD, fillvalue_index);
            
            % Get the long name attribute from the data field.
            long_name_index = matlab.io.hdf4.sd.findAttr(sdsID_MYD, 'long_name');
            long_name{i}=matlab.io.hdf4.sd.readAttr(sdsID_MYD, long_name_index);
            
            % Read units from the data field.
            units_index = matlab.io.hdf4.sd.findAttr(sdsID_MYD, 'units');
            units{i-2}=matlab.io.hdf4.sd.readAttr(sdsID_MYD, units_index);
            
            % Read scale_factor from the data field.
            scale_index = matlab.io.hdf4.sd.findAttr(sdsID_MYD, 'scale_factor');
            scale=matlab.io.hdf4.sd.readAttr(sdsID_MYD, scale_index);
            
            % Read offset from the data field.
            offset_index = matlab.io.hdf4.sd.findAttr(sdsID_MYD, 'add_offset');
            offset=matlab.io.hdf4.sd.readAttr(sdsID_MYD, offset_index);
            
            % Read the valid data range from the data field.
            valid_range_index = matlab.io.hdf4.sd.findAttr(sdsID_MYD, 'valid_range');
            valid_range=matlab.io.hdf4.sd.readAttr(sdsID_MYD, valid_range_index);
            
            % Replace the fill value with NaN.
            MYD(MYD==fillvalue)=NaN;
            
            % Mask values outside of valid_range.
            MYD(MYD<valid_range(1))=NaN;
            MYD(MYD>valid_range(2))=NaN;
            
            % Multiply scale and adding offset, the equation is "scale * (data-offset)".
            MYD=scale.*(MYD-offset);
            
            % Rotate the data as it is currently 360x180
            dims=length(size(MYD));
            switch dims
                case {1,2}
                    MYD=MYD';
                    
                case {3}
                    MYD_temp=zeros(size(MYD,2),size(MYD,1),size(MYD,3)).*NaN;
                    for z=1:size(MYD,3)
                        MYD_temp(:,:,z)=squeeze(MYD(:,:,z))';
                    end
                    MYD=MYD_temp;
                    
                case {4}
                    MYD_temp=zeros(size(MYD,2),size(MYD,1),size(MYD,3),size(MYD,4)).*NaN;
                    for z=1:size(MYD,3)
                        for c=1:size(MYD,4)
                            MYD_temp(:,:,z,c)=squeeze(MYD(:,:,z,c))';
                        end
                    end
                    MYD=MYD_temp;
            end
            
            % Commit the temporary MYD data to a struct
            eval(['MYD_struct.',sds_names{i},'=MYD;']);
            
            % Indicate that this is a variable worth taking a mean of between both satellites
            variable_marker(i)=1;
            
        else
            %if here, it means that the variable must be XDim or YDim. Populate the correct output
            if strcmp(sds_names{i},'XDim')
                longitudes=MYD;
            elseif strcmp(sds_names{i},'YDim')
                latitudes=MYD;
            else %else it must be one of the intervals and so commit it to the data
                eval(['data.',sds_names{i},'=MYD;']);
            end
        end
        
    end
    
    % close the files
    matlab.io.hdf4.sd.close(MYD_id);
end


%% Process the Terra MOD files
if MOD_flag==1
    % open the files
    MOD_id=matlab.io.hdf4.sd.start(filename_MOD);
    units=cell(1,length(sds_names));
    long_name=cell(1,length(sds_names));
    
    % loop through each SDS name,
    for i=1:length(sds_names)
        
        % extract the object index
        objIdx_MOD=matlab.io.hdf4.sd.nameToIndex(MOD_id,sds_names{i});
        
        % establish the SDS ID
        sdsID_MOD=matlab.io.hdf4.sd.select(MOD_id,objIdx_MOD);
        
        % load the data into memory
        MOD=double(matlab.io.hdf4.sd.readData(sdsID_MOD));
        
        if (sum([strcmp(sds_names{i},'XDim'),strcmp(sds_names{i},'YDim')])==0 && length(MOD)>45) %ignore XDim YDim and interval definitions (typcally 1X3/5/7/9/45 vectors)
            
            % Read fill value from the data field.
            fillvalue_index = matlab.io.hdf4.sd.findAttr(sdsID_MOD, '_FillValue');
            fillvalue=matlab.io.hdf4.sd.readAttr(sdsID_MOD, fillvalue_index);
            
            % Get the long name attribute from the data field.
            long_name_index = matlab.io.hdf4.sd.findAttr(sdsID_MOD, 'long_name');
            long_name{i}=matlab.io.hdf4.sd.readAttr(sdsID_MOD, long_name_index);
            
            % Read units from the data field.
            units_index = matlab.io.hdf4.sd.findAttr(sdsID_MOD, 'units');
            units{i-2}=matlab.io.hdf4.sd.readAttr(sdsID_MOD, units_index);
            
            % Read scale_factor from the data field.
            scale_index = matlab.io.hdf4.sd.findAttr(sdsID_MOD, 'scale_factor');
            scale=matlab.io.hdf4.sd.readAttr(sdsID_MOD, scale_index);
            
            % Read offset from the data field.
            offset_index = matlab.io.hdf4.sd.findAttr(sdsID_MOD, 'add_offset');
            offset=matlab.io.hdf4.sd.readAttr(sdsID_MOD, offset_index);
            
            % Read the valid data range from the data field.
            valid_range_index = matlab.io.hdf4.sd.findAttr(sdsID_MOD, 'valid_range');
            valid_range=matlab.io.hdf4.sd.readAttr(sdsID_MOD, valid_range_index);
            
            % Replace the fill value with NaN.
            MOD(MOD==fillvalue)=NaN;
            
            % Mask values outside of valid_range.
            MOD(MOD<valid_range(1))=NaN;
            MOD(MOD>valid_range(2))=NaN;
            
            % Multiply scale and adding offset, the equation is "scale * (data-offset)".
            MOD=scale.*(MOD-offset);
            
            % Rotate the data as it is currently 360x180
            dims=length(size(MOD));
            switch dims
                case {1,2}
                    MOD=MOD';
                    
                case {3}
                    MOD_temp=zeros(size(MOD,2),size(MOD,1),size(MOD,3)).*NaN;
                    for z=1:size(MOD,3)
                        MOD_temp(:,:,z)=squeeze(MOD(:,:,z))';
                    end
                    MOD=MOD_temp;
                    
                case {4}
                    MOD_temp=zeros(size(MOD,2),size(MOD,1),size(MOD,3),size(MOD,4)).*NaN;
                    for z=1:size(MOD,3)
                        for c=1:size(MOD,4)
                            MOD_temp(:,:,z,c)=squeeze(MOD(:,:,z,c))';
                        end
                    end
                    MOD=MOD_temp;
            end
            
            % Commit the temporary MYD data to a struct
            eval(['MOD_struct.',sds_names{i},'=MOD;']);
            
            % Indicate that this is a variable worth taking a mean of between both satellites
            variable_marker(i)=1;
            
        else
            %if here, it means that the variable must be XDim or YDim. Populate the correct output
            if strcmp(sds_names{i},'XDim')
                longitudes=MOD;
            elseif strcmp(sds_names{i},'YDim')
                latitudes=MOD;
            else %else it must be one of the intervals and so commit it to the data
                eval(['data.',sds_names{i},'=MOD;']);
            end
        end
        
    end
    
    % close the files
    matlab.io.hdf4.sd.close(MOD_id);
end

%% Combine both MYD and MOD should they both exist, else just use one of the variables.
if MYD_flag+MOD_flag==2
    
    for i=1:length(sds_names)
        if variable_marker(i)==1
            % Take a mean of this value across both the Terra and Aqua satellites
            MYD_temp=eval(['MYD_struct.',sds_names{i}]);
            MOD_temp=eval(['MOD_struct.',sds_names{i}]);
            
            % find the total number of data at each pixel to divide by
            nan_countMYD=zeros(size(MYD_temp))+~isnan(MYD_temp);
            nan_countMOD=zeros(size(MOD_temp))+~isnan(MOD_temp);
            divider=nan_countMYD+nan_countMOD;
            
            % set NaNs to 0 for the addition
            MYD_temp(isnan(MYD_temp))=0;
            MOD_temp(isnan(MOD_temp))=0;
            
            % take a mean
            Mean_data_for_both_terra_and_aqua=(MYD_temp+MOD_temp)./divider; %the divider will divide previously NaN values by 0, returning them to NaNs
            
            % Populate the output Data struct
            eval(['data.',sds_names{i},'=Mean_data_for_both_terra_and_aqua;']);
        end
    end
    
elseif (MYD_flag==1 && MOD_flag==0) %there was no MOD data
    for i=1:length(sds_names)
        if variable_marker(i)==1
            % Populate the output Data struct
            eval(['data.',sds_names{i},'=MYD_struct.',sds_names{i},';']);
        end
    end
    
elseif (MYD_flag==0 && MOD_flag==1) %there was no MYD data
    for i=1:length(sds_names)
        if variable_marker(i)==1
            % Populate the output Data struct
            eval(['data.',sds_names{i},'=MOD_struct.',sds_names{i},';']);
        end
    end
    
elseif (MYD_flag==0 && MOD_flag==0) %if there were no MYD or MOD
    disp([' WARNING: There were no daily data files for ',datestr_yyyymmdd])
    
end

%% outputs
if exist('data','var')
    Data=data;
    Latitudes=latitudes;
    Longitudes=longitudes;
    Units=units;
    Long_name=long_name;
else
    Data=[];
    Latitudes=[];
    Longitudes=[];
    Units=[];
    Long_name=[];
end

catch err
    disp(getReport(err,'extended'));
   error('wtf?!'); 
end

end
